### ISSUE TITLE
SOAR MOP template

### ISSUE THREAD

**Issue by KKruszynska** [LCOGT/mop#138]
The SOAR template in MOP is missing different slits and grating options.

**Comment by KKruszynska** [comment]
Actually other slit sizes and gratins are missing in the LCO Observe portal.

**Comment by rachel3834** [comment]
For the record, the AEON-SOAR operations team assured us that the software on the SOAR end looks at the contents of the read-out mode field in order to set the instrument configuration.  They apparently don't use the separate fields for slit width an grating, which is why those fields are not populated.  This seems rather unintuitive so I've asked the TOM Team to revise the UI display for SOAR to clarify this.  However, it's not actually broken, and observation requests should work provided the right read-out mode is set.  

I will update MOP when the revised version of the SOAR observation form is released by the TOM Toolkit, so closing this issue for now.
