### ISSUE TITLE
MOP upload data .csv format

### ISSUE THREAD

**Issue by ytsapras** [LCOGT/mop#59]
Under **Upload a data product**
 the example csv photometry file has 6 columns. Is that accurate? Maybe add the column names and format on the page directly?

**Comment by rachel3834** [comment]
Related to this, MOP's custom processor for spectroscopic csv files needs updating to the modern formats.  Accurate examples of the required file type should be given.

**Comment by rachel3834** [comment]
Since MOP has custom processors for both spectroscopy and photometry, I've implemented a customized template for data uploads, pointing to sample datafiles in our Github repo which meet MOP's formatting requirements. 

I've also updated MOP's spectroscopic processor to match a recent upgrade to the underlying TOM generic data processor, which now requires a 3-component tuple (timestamp, data and source_id) rather than the previous two-component tuple.  

This issue was fixed in 4.0.5.9.1
